name: OmniSell
description: $description
version: '${version}'

main: net.omni.sell.OmniSell
api-version: '1.13'
load: POSTWORLD

softdepend: [ ExcellentEconomy ]

depend: [ SuperiorSkyblock2 ]

authors: [ domninos ]

commands:
  omnisell:
    usage: /<command>
    description: Base command for OmniSell
    aliases: [osell, sellportal, sp]
