name: OmniSell
description: $description
version: '${version}'

main: net.omni.sell.OmniSell
api-version: '1.13'
load: POSTWORLD

softdepend: [ ExcellentEconomy, SuperiorSkyblock2 ]

authors: [ domninos ]
